認証機能のリファクタリング
toyokappa/knowledge-stocker pull request #20
Opened 2017-07-23 03:37 UTC by toyokappa

下記を実装しました。

1. ApplicationControllerにSessionsHelperを挿すのをやめる
2. 認証システムのブラックリストの設定
3. ユーザー編集機能の追加
4. アソシエーションを使用したコレクションの取得
5. Userの編集権限、Wordの編集権限、削除権限の追加
6. 権限ユーザーにのみ編集、削除等のリンクを表示させる

2017-07-23 05:04 UTC, yhirano55 requested changes

2017-07-23 05:04 UTC, yhirano55 commented on app/controllers/sessions_controller.rb
> +    end
メソッド名は、他に処理がないので、create_session と destroy_session で良さそう。
たとえば、最終ログイン日時などを、ログインする度に記録する場合は、次のように処理をまとめて、処理内容の意味がわかる命名として `login` や `signin` と付けたりしますね。

```ruby
def login(user)
  create_session_from(user)
  user.touch(:last_logged_in_at)
end
```

2017-07-23 05:04 UTC, yhirano55 commented on app/helpers/sessions_helper.rb
> -  end
コントローラを生成する毎にヘルパーが生成されますが、実際はそのmoduleは何も実装されないことが多いので、generatorの設定を変えて、生成されないようにした方がよかったりします。

可能だったら調べて、 `config/application.rb` で設定してみてください。

2017-07-23 05:04 UTC, yhirano55 commented on app/controllers/static_pages_controller.rb
> +  skip_before_action :authenticate_user, only: [:home]
クローズドなシステムな場合、ログインしていない場合は、 homeではなく、ログイン画面に遷移する方が一般的かなと思うのと、サインインとサインアップ以外は、基本的には通す必要があまりないように思いました。

2017-07-23 05:04 UTC, yhirano55 commented on app/controllers/users_controller.rb
> +    end
自分自身を更新するときは、findしなおさずにcurrent_userを使えばよさそう（他人のリソースを更新しないならばなおさら）。 `resources :users` ではなく `resource :user` と書いた場合、idの指定は不要となります。もう少しルーティングの理解を深めましょう。

2017-07-23 05:04 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    end
検索して、それがなかったらリダイレクトという処理は書かず、例外を発生させるのが妥当です。
適切な、HTTPステータスを返している意識をもってみるとよいかもしれません。

また、 `correct_user` というメソッド名と、書かれた処理はだいぶミスマッチです。「ユーザーを集める」というメソッド名でワードを取り扱っていることは非常に違和感があり、保守しにくそうです。

考えたうえで、 `correct` という単語を選んでいるかと思いますが、 内部でやっていることは `find` なので、そういう場合は `find_xxx` と命名すると、意図が伝わりやすそうです。

2017-07-23 05:04 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    @words = current_user.words.all
orderは指定しなくても大丈夫でしょうか? （scope作っていた気が）

2017-07-23 05:04 UTC, yhirano55 commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
`presence: true` は `present?` が true であることを保証するので、それと同時に `allow_nil: true` を書いている意図が分かりませんでした。更新の時に都合が悪くて変更したのかもしれませんが...。

2017-07-23 05:04 UTC, yhirano55 commented on app/views/users/edit.html.erb
> +<h1 class="center">ユーザー情報の編集</h1>
基本的に、i18nがあるので、viewには日本語を直接書き込むことはありません。

2017-07-23 05:04 UTC, yhirano55 commented on app/views/words/show.html.erb
> +  <% end %>
WordsControllerのindexは、current_userから引いているので、他人のリソースである場合は、考慮する必要がなさそうです。現在は次のようになっていますが、

```ruby
def show
  @word = Word.find_by(id: params[:id])
end
```

以下のようになるのが自然です。

```ruby
def show
  @word = current_user.words.find(params[:id])
end
```

2017-07-23 05:04 UTC, yhirano55 commented on app/views/users/edit.html.erb
> +<h1 class="center">ユーザー情報の編集</h1>
日本語が埋め込まれている箇所は、すべて修正したほうがよさそうです。

2017-07-23 05:04 UTC, yhirano55 commented on app/controllers/application_controller.rb
> +    end
userを主語として、何かを確認する場合は、 `current_user.same_as?(user)` みたいに書ける方が良くて、コントローラーやヘルパーに書くメソッドは、基本的に 主語が特定できないもの であることが多いです。

2017-07-23 05:51 UTC, yuemori reviewed
correct_userのところは @yhirano55 の言うとおり例外で処理したほうが良いと思いますが、やりたかったことに対して参考までに、って感じです。

例外処理はちょっと難しいかもしれないので、わからなかったらslackで質問してみてください。

2017-07-23 05:51 UTC, yuemori commented on app/controllers/users_controller.rb
> +    def correct_user
`correct_user` だと「編集できるのはcurrent_userのものだけである」というビジネスロジックの意図が伝わらないと思います。
`redirect_unless_current_user` / `require_current_user` / `only_current_user` / `check_current_user` みたいなのがよくあるかなあと。
（英語力低いんでもっと良いのあったらどなたか指摘してください 🙇 ）

current_userはcorrect_userでもいいんですけど、「correct_userってどうなったらcorrect_userなんだろう」っていう疑問が処理の内容を見ないとわからないですよね。
その点、current_userは一般的なので伝わりやすいです。

2017-07-23 05:51 UTC, yuemori commented on app/helpers/sessions_helper.rb
細かいですけど空行が謎な感じになってます

2017-07-23 05:51 UTC, yuemori commented on app/controllers/users_controller.rb
> +      @user = User.find(params[:id])
ユーザの検索をしてインスタンス変数に代入する処理をここでやってしまうのは良いアイデアではないです。
このメソッドの処理は「編集しようとしているものがcurrent_userのものかチェックする」のはずなので、ちゃんとactionを分離しましょう
（wordのところも同様）

2017-07-23 05:51 UTC, yuemori commented on app/controllers/words_controller.rb
> +    @words = current_user.words.all
処理内容は変わらないんであってもいいんですが、 `current_user.words` だけでも挙動は同じです。

2017-07-29 07:31 UTC, toyokappa commented
レビューいただいた点を修正しました。

1. 自動でhelperが作成されないように`config/application.rb`を変更
2. helperファイルの削除
3. ユーザーのリソースを`resource`で設定
4. 上記にともなるコントローラーの修正
5. `allow_nil`の削除（編集時に毎回パスワードを入力する問題の解決は以後実装）
6. Viewファイルの微調整
7. rubocopのインストール、設定（もくもく会でおすすめ頂きました）

下記は未実装。

- I18nによる日本語化（次回のPRで実装予定）
- `current_user?`を`same_as?`に変更（`current_user.same_as?`というようなメッソドの作り方が分かりませんでした）

2017-07-29 08:39 UTC, yhirano55 commented on Gemfile
> +  gem 'rubocop', require: false
導入はGoodなんですが、基本一回レビューした後は、それの直しだけにして、別PRで対応してもらえるとよさそうです（見る範囲が変わってしまうのでレビューしにくいから）

2017-07-29 08:43 UTC, yhirano55 commented on app/controllers/application_controller.rb
> +    @current_user ||= User.find_by(id: session[:user_id])
知っているかもしれないですが、 `||=` の意味は覚えた方がよいですね。

2017-07-29 08:46 UTC, yhirano55 commented on app/controllers/sessions_controller.rb
> +      create_session(user)
上にある `user` をローカル変数からメソッドにして、メモ化すれば、create_sessionは引数いらなくなるので、私の場合は、そう書いたりします（修正は不要です）

2017-07-29 08:47 UTC, yhirano55 commented on app/controllers/sessions_controller.rb
> +    @current_user = nil
destroy_sessionしたあとはたいていリダイレクトするので、@current_userにnilをセットしなくてもよいかなーとお思いますが、このままでも構いません（実践でこれを書いた場合、何を考慮しているの？と聞かれることはあるかと思います）

2017-07-29 08:51 UTC, yhirano55 commented on app/controllers/users_controller.rb
> +  end
セットする必要がなさそう。

2017-07-29 08:52 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +  end
メソッドの意味と処理がフィットしていない印象があります。 setされている対象は `@word` なので、 `set_word` だったり `find_word` あるいは `load_word` あたりが妥当かなーと思いました。

2017-07-29 08:59 UTC, yhirano55 commented on app/views/users/show.html.erb
> +<%= link_to "編集", edit_user_path(current_user) if current_user.same_as?(@user) %>
@user が current_user じゃないときってあります?

2017-07-29 09:05 UTC, yhirano55 commented on app/views/words/show.html.erb
> +  <% end %>
findしているwordが、 `current_user.words.find(params[:id])` ならば、自分以外のリソースが表示されることがないのかな?と思います。

2017-07-29 09:06 UTC, yhirano55 commented on config/application.rb
> +    end
js, cssもコントローラ毎に生成する必要はないので、追加してもよいかもしれませんね。

2017-07-29 09:24 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    if @word.knowledges.empty?
なんかこだわりあるっぽいけども、分岐する必要がなさそう。
やるとしても別のアプローチがいいんじゃないかな。

2017-07-29 09:41 UTC, yhirano55 commented
レビューだん。viewの制御不要っぽいので見直した方がよさそう。それができたら `same_as?` も不要になりそう。

2017-07-29 13:54 UTC, toyokappa commented
修正しました。

1. `set_current_user`、`set_current_user_words`の削除
2. `same_as?`の削除とそれに伴うViewの修正
3. `generators`の再セッティング（CSS、JS、Viewスペック、helperスペックの排除）

2017-07-29 14:00 UTC, yhirano55 commented on config/application.rb
> +      g.test_framework :rspec, view_specs: false, helper_specs: false
:+1:

2017-07-29 14:04 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    @word = current_user.words.find(params[:id])
メソッドをリネームした方がよさそう、という指摘だったのですが、before_actionをやめてしまったんですね。

2017-07-29 14:05 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    if @word.knowledges.empty?
emptyなら3つbuildして、それ以外は1つbuildする、のは何かこだわりあるのでしょうか?

2017-07-29 14:18 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    @word = current_user.words.find(params[:id])
RailsのScaffoldの場合だと `set_#{resource_name}` みたいな命名になっていますね。なので、このコントローラの場合だと `set_word` あたりですかね。

```ruby
    # Use callbacks to share common setup or constraints between actions.
    def set_<%= singular_table_name %>
      @<%= singular_table_name %> = <%= orm_class.find(class_name, "params[:id]") %>
    end
```

2017-07-29 14:37 UTC, toyokappa commented on app/controllers/words_controller.rb
> +    @word = current_user.words.find(params[:id])
`@user = current_user`をセットしない、という意味と混同していました。メソッド名変えて、before_actionを設定し直します。

2017-07-29 14:49 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    @word = current_user.words.find(params[:id])
なるほど。いいねいいね。コードレビューは、そういう感じですよ（テレビみながら書いてる）

2017-07-29 14:52 UTC, toyokappa commented on app/controllers/words_controller.rb
> +    if @word.knowledges.empty?
Word登録後、初回はURLを一気に追加するかもしれないから枠を3つ追加しよう。
その後は一気にURLを追加することもないから、1つずつ枠を追加する仕様にしよう。
という特に根拠はないですが、自分がサービスを使ったときの状況をイメージして実装しました。

2017-07-29 15:00 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    if @word.knowledges.empty?
なるほど。これは企画的な話ですが、現段階ではそこまでUXを固定せずに、調整は別のフェーズで対応する方がよいかもしれませんよ。

2017-07-29 15:04 UTC, toyokappa commented on app/controllers/words_controller.rb
> +    if @word.knowledges.empty?
了解です。そしたら、初回でも1つbuildする設定にして、サービスがしっかり形になった後にUXを真剣に考えて、使いやすい仕様に切り替えるようにします。

2017-07-29 15:16 UTC, toyokappa commented
修正しました。

1. `current_user`の使い方を見直し（`@user = current_user`を使わない実装）
2. `words_controller`に`before_action`を追加
3. `words_controller`のeditアクションをシンプル化

2017-07-29 15:30 UTC, yhirano55 commented on app/views/users/show.html.erb
> +<%= link_to "編集", edit_user_path(current_user) %>
いいですね

2017-07-29 15:33 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    @word.knowledges.build
いいですね。

2017-07-29 15:35 UTC, yhirano55 commented
LGTMですが、他のコメント欄にリプライするか（必要なら追加対応）などした後にまーじした方がいいですね。

2017-07-29 15:44 UTC, toyokappa commented on app/helpers/sessions_helper.rb
> -  end
ありがとうございます！generatorの設定を調べて、設定してみました。

2017-07-29 15:47 UTC, toyokappa commented on app/controllers/static_pages_controller.rb
> +  skip_before_action :authenticate_user, only: [:home]
クローズドな場合は基本、ログイン画面に遷移する旨、理解しました。ありがとうございます！

2017-07-29 15:50 UTC, toyokappa commented on app/controllers/users_controller.rb
> +    end
ありがとうございます！`resources`と`resource`の違いを理解することが出来ました。以降は暇を見つけてにルーティングの理解を深めます。

2017-07-29 15:51 UTC, toyokappa commented on app/controllers/words_controller.rb
> +    @words = current_user.words.all
scopeはKnowledgeで指定をしていたので、コチラはこのまま進めさせていただきます。

2017-07-29 15:53 UTC, toyokappa commented on app/controllers/words_controller.rb
> +    end
ありがとうございます。例外についての勉強、まだやりきれていないので、これも早期に頭に詰め込むリストに追加します。

メソッド名の付け方も指摘が多いポイントなので、注意して進めるようにします。

2017-07-29 15:55 UTC, toyokappa commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
編集画面にpasswordとpassword_confirmationが表示され、それを入力しないと編集が出来ない問題が発生しています。それを一時的に処理するコードでしたが、やはり、美しくないですよね。。一旦それを仕様として進めるのですが、解決方法は検討します。

2017-07-29 15:56 UTC, toyokappa commented on app/views/users/edit.html.erb
> +<h1 class="center">ユーザー情報の編集</h1>
ありがとうございます。I18nは別のPRで対応する様にします。対応の仕方は別途相談させて頂けますと幸いです。

2017-07-29 15:57 UTC, toyokappa commented on app/views/words/show.html.erb
> +  <% end %>
記載いただいたコードを活用させていただきました。ありがとうございます！

2017-07-29 16:00 UTC, toyokappa commented on app/controllers/application_controller.rb
> +    end
Slackでも補足頂きありがとうございました。Modelにメソッドを書く場合とControllerへメソッドを書く場合のところは、もう少し勉強します。（ここがスッキリと腹落ちしたら、気持ちいいだろうなぁ。。）

2017-07-29 16:02 UTC, toyokappa commented on app/controllers/users_controller.rb
> +    def correct_user
ありがとうございます！メソッドのビジネスロジックを意識した命名については考える癖付けから立て直しますので、今後も気になった際はご指摘頂けますと幸いです。

2017-07-29 16:03 UTC, toyokappa commented on app/controllers/users_controller.rb
> +      @user = User.find(params[:id])
actionの分離、理解しました。これも上記のビジネスロジックの問題と紐づく話だと思いますので、同様に注意をして進めます。ありがとうございます！

2017-07-29 16:05 UTC, toyokappa commented on app/helpers/sessions_helper.rb
確認せずにPRを上げてしまい、失礼致しました。。以後、気をつけます。。

2017-07-29 16:06 UTC, toyokappa commented on app/controllers/words_controller.rb
> +    @words = current_user.words.all
ありがとうございます！挙動確認しました！

2017-07-29 16:07 UTC, toyokappa commented on Gemfile
> +  gem 'rubocop', require: false
コチラ失礼致しました。PRの内容と関連してるかどうかの考えは持ってコードの修正や追加をするように致します。

2017-07-29 16:09 UTC, toyokappa commented on app/controllers/application_controller.rb
> +    @current_user ||= User.find_by(id: session[:user_id])
ありがとうございます。これなんだっけ、となった時にこのページを見返すようにしています。
https://railstutorial.jp/chapters/basic_login?version=5.0#aside-or_equals

2017-07-29 16:11 UTC, toyokappa commented on app/controllers/sessions_controller.rb
> +      create_session(user)
ありがとうございます。メモ化。。これは要勉強です。勉強後修正するようにします！

2017-07-29 16:11 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +    end
早期に、でもないかな。今後開発していくなかで登場してきたらでよさそう。
命名も慣れではあるけど、伊藤淳一さんのQiitaの記事とか目を通しておくといいかもしれませんね。

2017-07-29 16:13 UTC, toyokappa commented on app/controllers/sessions_controller.rb
> +    @current_user = nil
なるほど、ありがとうございます。これは今回のPRで修正するようにします。

2017-07-29 16:13 UTC, yhirano55 commented on app/controllers/application_controller.rb
> +    @current_user ||= User.find_by(id: session[:user_id])
`nilガード` って呼ばれるRubyの基本表現で、頻繁に使うので理屈含めて覚えた方がいいですよ。

2017-07-29 16:14 UTC, yhirano55 commented on app/controllers/sessions_controller.rb
> +      create_session(user)
メモリにキャッシュする、という意味ですね。これもRubyだと頻繁に使います。

2017-07-29 16:14 UTC, toyokappa commented on app/controllers/users_controller.rb
> +  end
こちらもSlackで補足いただきありがとうございました。セットしない形で実装をしました！

2017-07-29 16:16 UTC, toyokappa commented on app/controllers/words_controller.rb
> +  end
メソッド名＝処理ですね。ありがとうございます。set_wordで設定をさせていただきました！

2017-07-29 16:20 UTC, yhirano55 commented on app/controllers/words_controller.rb
> +  end
いいね

2017-07-29 16:23 UTC, yhirano55 commented
あとは修正したらレビューなしでマージしてよさそうです😁 
ちょっと大変だったと思いますけど、おつかれさまでした。

2017-07-30 05:50 UTC, toyokappa commented on app/views/users/show.html.erb
> +<%= link_to "編集", edit_user_path(current_user) if current_user.same_as?(@user) %>
ありがとうございます。確かに、@userがcurrent_userじゃない時はないですね。修正しました！

2017-07-30 05:50 UTC, toyokappa commented on app/views/words/show.html.erb
> +  <% end %>
ありがとうございます。コチラも同様に自分のリソース以外が表示されることがないので修正しました。

2017-07-30 05:51 UTC, toyokappa commented on config/application.rb
> +    end
不要なファイルは一旦generatorの設定から外します！ありがとうございます！

2017-07-30 05:53 UTC, toyokappa commented on app/controllers/application_controller.rb
> +    @current_user ||= User.find_by(id: session[:user_id])
nilガードですね。ありがとうございます。メモしたので後ほど詳しく調べます！

2017-07-30 05:54 UTC, toyokappa commented on app/controllers/sessions_controller.rb
> +      create_session(user)
ありがとうございます。「メモリをキャッシュする」これも基礎知識として理解するようにします。

2017-07-30 05:58 UTC, toyokappa commented
ありがとうございます。修正を掛けたのでマージして次に進めます！
今回もありがとうございました！引き続きよろしくお願い致します。

2017-07-30 05:58 UTC, merged

2017-07-30 15:02 UTC, yhirano55 commented on app/controllers/users_controller.rb
> +                                 :password_confirmation)
https://github.com/toyokappa/knowledge-stocker/blob/master/config/initializers/filter_parameter_logging.rb#L4

指摘しようと思っていて忘れましたが、上記のフィルタにpassword_confirmationを追加した方がいいですね。理由はググってみてください。

2017-07-31 22:24 UTC, toyokappa commented on app/controllers/users_controller.rb
> +                                 :password_confirmation)
ありがとうございます。フィルタの設定ぐぐってみました。この後I18nのPRを上げるのですが、その後のPRで対応をしたいと思います。